{{- if .Values.pullSecret.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhaii.pullSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhaii.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerConfigJson | b64enc }}
{{- end }}
